# -*- coding: utf-8 -*-
"""SSM-ML1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AInA7vOnZ_t74hESa0tc0_8XokAB12eN
"""

a=5
b=20
print(a+b)

"""Addition of two numbers"""